### ISSUE TITLE
Infografia_Gonzalez_Morales_Ximena

### ISSUE THREAD

**Issue by LeinnaMora** [SistemasTecTlaxiaco/infografia-LeinnaMora#1]
[Infografia_Ximena_Gonzalez_Morales.pdf](https://github.com/user-attachments/files/16821498/Infografia_Ximena_Gonzalez_Morales.pdf)

**Comment by Proyect-A16** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:12/14
Referencias:13/14
Presentación:13/14
Calificación Final: 19/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
